BKNDLSS-28935 Alert
Backendless/ui-builder-library pull request #14
Opened 2022-07-08 21:11 UTC by StasivPavlo

2022-07-11 11:06 UTC, v-excelsior commented
thumbnail.png is needed for publishing, and I'm not sure if we should include it in a pull request.
At same time screenshots of components variants should be posted in the PR description(when opening PR)

2022-07-11 11:09 UTC, v-excelsior requested changes

2022-07-11 11:09 UTC, v-excelsior commented on components/bl-alert-component/README.md
> +# Alert
add screenshots please, and don't forget to check all points in checklist https://github.com/Backendless/ui-builder-library/wiki/PR-Checklist

2022-07-11 11:09 UTC, v-excelsior commented on components/bl-alert-component/styles/index.less
> +@bl-customComponent-alert-errorBackgroundColor: rgb(253, 237, 237);
use rgb or hex everywhere, don't mix them when it not needed.

2022-07-14 23:33 UTC, v-excelsior requested changes

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +  const [alertAnimation, setAlertAnimation] = useState('');
isClosing

and in useAlertClasses(rename it):

```
const classes = [ 'alert', variant, `${variant}--${messageType}`]

classes.push( isClosing ? 'alert-open' : 'alert-close')

return classes.join(' ')
```

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +    }, (speedCloseAnimation * 1000) - 50);
why here -50 ?

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +    speedCloseAnimation,
closing duration

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +    isCloseButtonVisibility,
closeButtonVisibility or isCloseButtonVisinle

I prefer first

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +  const alertClass = useAlertClass(variant, messageType, alertAnimation);
const classes = useAlertClasses(...)

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +          {messageTitle && (
in one row?

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +            variants={variant}
variant={ variant }

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/index.js
> +            variants={variant}
As I see editor config is not applied.

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/subcomponents.js
> +  const {
in one row, or destructure on arguments

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/src/subcomponents.js
> +  switch (typeAlert) {
outside of a component
```
const IconsMap = {
'succes': SuccesIcon
....
}
```
and here
```
const Icon = IconsMap[variant]

return <Icon props={props}>
```

SuccesIcon - is component

2022-07-14 23:33 UTC, v-excelsior commented on components/bl-alert-component/styles/index.less
> +@bl-customComponent-alert-fontSize: 0.875rem;
could we use `px`? i think there could be some collisions if we put this component into some container with a defined `font-size`

2022-07-18 13:40 UTC, Valodya commented on components/bl-alert-component/component.json
> +      "id": "closeButtonAction",
`closeButtonAction` => `close`

2022-07-18 13:42 UTC, Valodya commented on components/bl-alert-component/src/icons.js
> +const SuccessIcon = ({ variant }) => {
function declaration is preferable for components 

```
function SuccessIcon ({ variant }) {
```

2022-07-18 13:42 UTC, Valodya commented on components/bl-alert-component/src/icons.js
> +      viewBox="0 0 24 24"
aria-hidden="true"
 viewBox="0 0 24 24">
   ... children components

2022-07-18 13:43 UTC, Valodya commented on components/bl-alert-component/component.json
> +      "name": "onCloseButton",
onCloseButton => onClose

2022-07-18 13:44 UTC, Valodya commented on components/bl-alert-component/src/index.js
> +  const [isAlertVisible, setIsAlertVisible] = useState(true)
```
  const [isAlertVisible, setIsAlertVisible] = useState(true)
  const [isClosing, setIsClosing] = useState(false)

  const classes = useAlertClasses(variant, messageType, isClosing)
  const classesTitle = useTextClass('alert__title', variant, messageType)
  const classesAlertText = useTextClass('alert__text', variant, messageType)

```

2022-07-18 13:45 UTC, Valodya commented on components/bl-alert-component/src/index.js
> +  component.closeButtonAction = () => {
`component.close = () => {`

2022-07-18 13:46 UTC, Valodya commented on components/bl-alert-component/src/index.js
> +    }, (closingDuration * 1000))
does make sense to have `closingDuration ` in milliseconds instead of seconds?

2022-07-18 13:49 UTC, Valodya commented on components/bl-alert-component/src/index.js
> +    setIsClosing(isAlertVisible)
it's not clear for me, why do set `setIsClosing(true)` if the alert is visible 

```
useEffect(() => {
    setIsClosing(isAlertVisible)
  }, [isAlertVisible])
```

and then set it `false` when actually it's going to be closed 

```
 component.closeButtonAction = () => {
    setIsClosing(false)

  ...
```

2022-07-18 13:52 UTC, Valodya commented on components/bl-alert-component/src/index.js
> +      <div
```
 <div className={ classes } style={ { animationDuration: `${ closingDuration }s` } }>
```

2022-07-18 13:53 UTC, Valodya commented on components/bl-alert-component/src/subcomponents.js
> +export const AlertButton = (props) => {
```
export function AlertButton({ onCloseButton, variant }) {
```

2022-07-20 18:24 UTC, merged