BKNDLSS-29018 Simple Modal
Backendless/ui-builder-library pull request #15
Opened 2022-07-18 11:58 UTC by StasivPavlo

![input_dark-fire](https://user-images.githubusercontent.com/99363993/179505748-c17d73cc-ee96-4373-8256-823870f1aa53.png)
![input](https://user-images.githubusercontent.com/99363993/179505756-25662530-2e17-4da9-9f72-3ee64b69eb1a.png)
![input_active](https://user-images.githubusercontent.com/99363993/179505758-7e0803db-639a-48e8-96a9-57706bd4dbfa.png)
![alert](https://user-images.githubusercontent.com/99363993/179505762-1cf6e98b-cc67-4379-b6f4-92b421455077.png)
![confirm](https://user-images.githubusercontent.com/99363993/179505763-e7f13b19-0c91-40e0-a857-c1e3a8a28daa.png)
![input_dark](https://user-images.githubusercontent.com/99363993/179505766-7491f4b5-a991-4260-8ec2-083d6d4d3c96.png)

2022-07-18 22:48 UTC, v-excelsior requested changes

2022-07-18 22:48 UTC, v-excelsior commented on components/bl-simpleModal-component/component.json
> +  "description": "",
add description, please check PR checklist

2022-07-18 22:48 UTC, v-excelsior commented on components/bl-simpleModal-component/component.json
> +      "handlerDescription": "This is a handler for the logic to determine the title for SImple Modal."
This is a handler for the logic to determine the title.

2022-07-18 22:48 UTC, v-excelsior commented on components/bl-simpleModal-component/component.json
> +      "handlerDescription": "This is a handler for the logic to determine the text for SImple Modal."
text -> content

2022-07-18 22:48 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +          { titleModal && (
In external component?

2022-07-18 22:48 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +            onSubmitButton={ onSubmitButton }
```
onClose={ onClose }
onSubmit={ onSubmit }
```

2022-07-18 22:48 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +  if (isModalOpen) {
into `useEffect` with `isModalOpen` deps

2022-07-18 22:48 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +    setIsClosing(false);
When we close the modal window that must be in 'closing' state, so for me, it's not logical when we close the modal window but set isClosing to false.

2022-07-19 11:14 UTC, v-excelsior commented on components/bl-simpleModal-component/component.json
> +      "name": "textModal",
"name": "content",
"label": "Contentl",
"handlerId": "contentLogic",
"handlerLabel": "Content Logic",

2022-07-19 11:15 UTC, v-excelsior commented on components/bl-simpleModal-component/component.json
> +      "name": "placeholderText",
placeholderText -> placeholder

2022-07-19 11:16 UTC, v-excelsior commented on components/bl-simpleModal-component/component.json
> +      "name": "submitButtonLabel",
all labels should be near each other

2022-07-19 11:19 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +import { SimpleModalButton, SimpleModalContainer, SimpleModalTitle } from './subcomponents';
Button, Container, Title

2022-07-19 20:34 UTC, v-excelsior commented on components/bl-simpleModal-component/styles/index.less
> +
remove empty line

2022-07-19 20:35 UTC, v-excelsior commented on components/bl-simpleModal-component/README.md
> +<dd>Allows select type of Simple Modal (Alert, Prompt, Confirm). Default value 'Alert'.</dd>
Allows select type of Simple Modal ("alert", "prompt", "confirm"). Default value "alert".

2022-07-19 20:38 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +          { title && (<Title title={ title }/>) }
just `<Title title={ title }/>`

and in component
```
if(!title) {
 return null
}
```

2022-07-19 20:40 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +  const {
in one line

2022-07-19 20:45 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +      document.body.classList.toggle('active-modal');
Please read how classList.toggle works

2022-07-19 20:47 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +  const {
in one line

2022-07-27 08:50 UTC, v-excelsior requested changes

2022-07-27 08:50 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +          onInputValue={ setInputValue }
onInputValue onInputChange onChange onInputValueChange - could we make all this handler names consistent?

2022-07-27 08:50 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +  const {
in one line

2022-07-27 08:50 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +}
```
export function Title({ content }) {
  if (!content) {
    return null;
  }

  return (
    <h2 className="simple-modal__title"> { content } </h2>
  );
}
```

2022-07-27 08:50 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +  if (title) {
may be `!title`?

2022-07-27 08:50 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +  const handlerSubmitted = () => {
onSubmitHandler

2022-07-27 08:50 UTC, v-excelsior commented on components/bl-simpleModal-component/src/subcomponents.js
> +      { (type === 'prompt' || type === 'confirm') && (
Modal types should be constant

2022-07-27 22:26 UTC, StasivPavlo commented on components/bl-simpleModal-component/src/index.js
> +  const [isClosing, setIsClosing] = useState(true);
component by default is closed. isClosing = true it means that the component is closed. isClosing needed for activating closing animation. Only "display" and "isModalOpen" are responsible for the visibility of the component.

2022-07-28 10:21 UTC, StasivPavlo commented on components/bl-simpleModal-component/src/index.js
> +    document.body.classList.toggle('active-modal', isModalOpen);
if the actions of both components are activated together

2022-08-01 11:58 UTC, v-excelsior commented on components/bl-simpleModal-component/src/index.js
> +  const [isClosing, setIsClosing] = useState(true);
>isClosing = true it means that the component is closed.

The reason I ask about it "is closing" - does not mean "it closed now", it mean's "it in the closing process now", that grammatically incorrect.
![image](https://user-images.githubusercontent.com/15347646/182142376-b9a330be-aa5d-4289-beb0-413bd4ea3e42.png)

2022-08-03 19:37 UTC, Valodya commented on components/bl-simpleModal-component/src/index.js
> +    document.body.classList.toggle('active-modal', isOpen);
should not this component use https://reactjs.org/docs/portals.html ?

2022-08-04 07:27 UTC, Valodya commented on components/bl-simpleModal-component/src/subcomponents.js
> +export function Button(props) {
Button => Buttons/Controls/ModalButtons/ModalControls?

2022-08-04 07:30 UTC, Valodya commented on components/bl-simpleModal-component/styles/index.less
> +  z-index: 1;
I assume some components might have higher z-index and as a result they can overlay the modal 

however, with using ReactProtal the problem should not appear

2022-08-04 18:57 UTC, Valodya commented on components/bl-simpleModal-component/src/modal.js
> +  useEffect(() => {
```
useEffect(() => {
    document.body.appendChild(root);

    return () => {
      document.body.removeChild(root);
    };
  });
```

2022-08-05 08:58 UTC, merged