MARKET-1464 Knob
Backendless/ui-builder-library pull request #156
Opened 2022-11-08 16:33 UTC by addKiwi

![image](https://user-images.githubusercontent.com/29707734/200622065-1fc142fe-fca7-4948-a5b1-55100bd2d661.png)
![image](https://user-images.githubusercontent.com/29707734/200622176-c72fbc0a-078e-4bf3-b2a9-8af83ce719a0.png)

2022-11-09 09:50 UTC, serhmel commented on components/bl-knob-component/src/index.js
> +export default function MyCustomComponent({ component, eventHandlers, appData, pageData, parentDataModel }) {
please, rename it `MyCustomComponent`

can we remove `appData, pageData, parentDataModel ` ?

2022-11-09 09:50 UTC, serhmel commented on components/bl-knob-component/src/index.js
> +  });
```suggestion
  Object.assign(component, {
    setValue   : value => setKnobValue(value),
    setReadOnly: readOnly => setKnobReadOnly(readOnly),
    setDisabled: disabled => setKnobDisabled(disabled),
  });
```

2022-11-09 09:50 UTC, serhmel commented on components/bl-knob-component/src/index.js
> +    const value = e.value;
empty line after variables

2022-11-09 09:50 UTC, serhmel commented on components/bl-knob-component/src/index.js
> +    eventHandlers.onChange({ data: value });
const { onChange } = eventHandlers;

and then

onChange({ data: value });

2022-11-09 09:50 UTC, serhmel commented on components/bl-knob-component/src/index.js
> +    <div className={ cn('bl-customComponent-Knob', classList) }>
add `style` property from `component`

2022-11-09 09:50 UTC, serhmel commented on components/bl-knob-component/README.md
> +  <img src="./thumbnail.png" alt="main thumbnail" width="100"/>
```suggestion
  <img src="./thumbnail.png" alt="main thumbnail" width="780"/>
```
it will be useful when Vlad change thumbnail

2022-11-11 20:39 UTC, v-excelsior requested changes

2022-11-11 20:39 UTC, v-excelsior commented on components/bl-knob-component/src/index.js
> +  const [knobReadOnly, setKnobReadOnly] = useState(!!readOnly);
Why do we need `!!`?

2022-11-11 20:39 UTC, v-excelsior commented on components/bl-knob-component/component.json
> +      "handlerLabel": "Set Max Logic",
Max Value Logic?

2022-11-11 20:39 UTC, v-excelsior commented on components/bl-knob-component/component.json
> +      "handlerLabel": "Set Min Logic",
Min Value Logic?

2022-11-11 20:39 UTC, v-excelsior commented on components/bl-knob-component/component.json
> +          "label": "Data"
`value`

and

`Changed Value`

2022-11-11 20:39 UTC, v-excelsior commented on components/bl-knob-component/README.md
> +  <img src="./thumbnail.png" alt="main thumbnail" width="780"/>
Looks not pretty good, could you add an image with high resolution?

2022-11-11 20:39 UTC, v-excelsior commented on components/bl-knob-component/src/index.js
> +    initialValue, readOnly, disabled, setMax, setMin, step, dial, valueTemplate, size, valueColor, rangeColor, display,
setMax and setMin - sound like setter functions
I prefer minValue and maxValue

2022-11-11 20:39 UTC, v-excelsior commented on components/bl-knob-component/src/index.js
> +    onChange({ data: value });
There should be

`onChange({ value });`

2022-11-18 16:32 UTC, merged