MARKET-1512 QR Scanner component
Backendless/ui-builder-library pull request #166
Opened 2022-11-28 17:04 UTC by serhmel

![Screenshot_1](https://user-images.githubusercontent.com/93279075/204337243-bef59cef-22c1-4268-b2b1-5f5cd7178ef4.png)
<img width="960" alt="Screenshot_5" src="https://user-images.githubusercontent.com/93279075/204337316-49e2606e-590a-497c-9972-b64f4efa9926.png">

UI Builder Preview:
![ui_builder_preview](https://user-images.githubusercontent.com/93279075/204337399-c599974e-db6f-4aea-960e-bd402345372b.png)

2022-11-28 19:41 UTC, Saharij reviewed
LGTM🔥

2022-12-08 16:42 UTC, v-excelsior requested changes

2022-12-08 16:42 UTC, v-excelsior commented on components/bl-qrScanner-component/src/helpers.js
> +  const updateFlash = () => {
useCallback

2022-12-08 16:43 UTC, v-excelsior commented
LGTM :thinking:

2022-12-08 16:52 UTC, v-excelsior requested changes

2022-12-08 16:52 UTC, v-excelsior commented on components/bl-qrScanner-component/src/helpers.js
> +    .then(result => onDecodeSuccess({ decodedQRCode: result.data }))
```suggestion
    .then(({data}) => onDecodeSuccess({ decodedQRCode: data }))
```

2022-12-08 16:52 UTC, v-excelsior commented on components/bl-qrScanner-component/styles/index.less
> +  button, label {
Try to avoid using element selectors. Use classes where it possible.

2022-12-08 16:52 UTC, v-excelsior commented on components/bl-qrScanner-component/src/index.js
> +    <label>
Is it focusable by tab?

2022-12-09 15:53 UTC, serhmel commented on components/bl-qrScanner-component/src/index.js
> +    <label>
It wasn't, but now it's focusable.

2022-12-13 09:55 UTC, Valodya approved these changes

2022-12-13 09:55 UTC, merged