MARKET-1586 ReCaptcha
Backendless/ui-builder-library pull request #187
Opened 2023-01-10 13:59 UTC by StasivPavlo

2023-01-11 16:49 UTC, addKiwi commented on components/bl-reCaptcha-component/README.md
> +## Action
Actions

2023-01-11 16:49 UTC, addKiwi commented on components/bl-reCaptcha-component/README.md
> +
I think Settings should be here
[example](https://github.com/Backendless/ui-builder-library/tree/main/components/bl-mapbox-component#settings)

2023-01-17 21:44 UTC, v-excelsior requested changes

2023-01-17 21:44 UTC, v-excelsior commented on components/bl-reCaptcha-component/README.md
> +ReCaptcha is a component of Backendless UI-Builder designer. This allows you to upgrade your security from bots when need to send some form
Please, adapt text from their site

> reCAPTCHA is a free service that protects your website from spam and abuse. reCAPTCHA uses an advanced risk analysis engine and adaptive CAPTCHAs to keep automated software from engaging in abusive activities on your site. It does this while letting your valid users pass through with ease.

2023-01-17 21:44 UTC, v-excelsior commented on components/bl-reCaptcha-component/README.md
> +| Get Token     |        | `String`: can get when the user passed captcha |
On Token Sent
On Pass(ed) - not sure which variant is correct

2023-01-17 21:44 UTC, v-excelsior commented on components/bl-reCaptcha-component/README.md
> +![](example-images/api-service-captcha-codeless.jpg)
Hide your test key from this image

2023-01-17 21:44 UTC, v-excelsior commented on components/bl-reCaptcha-component/src/index.js
> +  const Captcha = SizeCaptcha[size];
size -> type

2023-01-17 21:44 UTC, v-excelsior commented on components/bl-reCaptcha-component/src/index.js
> +    <div className={ cn('bl-customComponent-reCaptcha', classList) } style={ style }>
If it not in popover when visible - add root ref(component.el)

2023-01-17 21:44 UTC, v-excelsior commented on components/bl-reCaptcha-component/src/index.js
> +import { ReCaptcha } from './re-captcha';
Need to add an error callback with action On Error

2023-02-03 15:07 UTC, v-excelsior requested changes

2023-02-15 17:16 UTC, merged