BKNDLSS-29102 Pagination
Backendless/ui-builder-library pull request #19
Opened 2022-07-27 14:27 UTC by StasivPavlo

![thumbnail](https://user-images.githubusercontent.com/99363993/181272963-edea6803-185b-47fb-ab57-308abb5a88a8.png)
![Screenshot_2](https://user-images.githubusercontent.com/99363993/181272977-550bcf5b-0167-44de-9c7f-a79198804e0b.png)
![Screenshot_3](https://user-images.githubusercontent.com/99363993/181272979-4abe2c3f-6443-454d-a0ad-781210146d37.png)
![Screenshot_4](https://user-images.githubusercontent.com/99363993/181272984-eaba5af1-a937-4f8b-adf0-e62003784582.png)

2022-07-28 13:11 UTC, addKiwi requested changes

2022-08-03 07:53 UTC, v-excelsior requested changes

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/component.json
> +      "name": "countPages",
countPages - pageCount

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/component.json
> +          "value": "",
I'm not sure, but sometime we have a problem with empty values in designer settings. Could you check if changing this property in designer works good?

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/component.json
> +      "name": "isNextButton",
isNextButton -> isNextButtunVisible
same for other

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/component.json
> +      "label": "Go Next Page"
Go to Next Page
Same for other

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/index.js
> +  const pages = usePagination(countPages, currentPage, siblingCount);
Do we need `pages` here? I think we could manipulate only pageCount(countPages)

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/use-pagination.js
> +      let rightItemCount = 3 + 2 * siblingCount;
I think there could be const, also check it for other variables.

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/use-pagination.js
> +
redundant empty line

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/use-pagination.js
> +    const rightSiblingIndex = Math.min(currentPage + siblingCount, countPages);
countPages - pageCount 

Rename it everywhere in PR

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/helpers.js
> +export const paginationStyle = {
Do we need it? Could we just rename classes in less to get rid of it?

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/buttons-svg.js
> +export function BackArrowSvg({ size }) {
Is it icon? If yes -> ArrowBackIcon, ArrowNextIcon, FIrstPageIcon, LastPageIcon

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/buttons-svg.js
> +export function NextArrowSvg({ size }) {
Not important, but I prefer arrow style for functional components like this.

```
export const NextArrowSvg = ({ size }) => (
    <svg
      className={ cn('pagination__control-button-svg', { [`pagination__control-button-svg--${ size }`]: size }) }
      focusable="false"
      aria-hidden="true"
      viewBox="0 0 24 24">
      <path d="M10 6L8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6z"></path>
    </svg>
  );

```

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/helpers.js
> +export const useControlButtonClass = (isDisabled, variant, paginationSize) => useMemo(() => {
useControlButtonClasses

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/index.js
> +        <PageButtonList
PageList

2022-08-03 07:53 UTC, v-excelsior commented on components/bl-pagination-component/src/helpers.js
> +export const usePageButtonListClass = (currentPage, page, variant, paginationSize) => useMemo(() => {
usePageListClasses

2022-08-03 17:08 UTC, v-excelsior requested changes

2022-08-03 17:08 UTC, v-excelsior commented on components/bl-pagination-component/src/index.js
> +        />
```suggestion
        { isFirstPageButtonVisible && (
          <FirstPageButton
            isFirstPageButtonVisible={ isFirstPageButtonVisible }
            onGoFirst={ onGoFirst }
            currentPage={ currentPage }
            paginationSize={ size }
            variant={ variant }
          />
        )}
```

Same for other.

2022-08-04 10:03 UTC, Valodya commented on components/bl-pagination-component/src/helpers.js
> +export const useControlButtonClasses = (isDisabled, variant, paginationSize) => useMemo(() => {
```
const { cn } = BackendlessUI.CSSUtils

export const useControlButtonClasses = (isDisabled, variant, paginationSize) => {
return cn('pagination__control-button', variant, {
  'pagination__control-button--disabled': isDisabled,
  [`${ variant }--${ paginationSize }`]: paginationSize
})
}

```

2022-08-04 10:09 UTC, Valodya commented on components/bl-pagination-component/.gitignore
> +/dist/
this file can be removed I guess

2022-08-04 10:11 UTC, Valodya commented on components/bl-pagination-component/src/helpers.js
> +export const usePageListClasses = (currentPage, page, variant, paginationSize) => useMemo(() => {
the same here

or, perhaps we can move this into particular components since it takes a couple lines

2022-08-04 10:13 UTC, Valodya commented on components/bl-pagination-component/src/subcomponents.js
> +import { DOTS, usePagination } from './use-pagination';
I would rename the file from `subcomponents` to `buttons`

2022-08-04 10:15 UTC, Valodya commented on components/bl-pagination-component/src/use-pagination.js
> +    const totalPageNumbers = siblingCount + 5;
can we create constants for these magic numbers `5/2/3`?

2022-08-25 12:51 UTC, merged