BKNDLSS-29123 Multiple Select
Backendless/ui-builder-library pull request #20
Opened 2022-07-27 18:23 UTC by Saharij

<img width="312" alt="Screenshot 2022-07-27 at 21 20 26" src="https://user-images.githubusercontent.com/56361878/181344308-c44f2cc9-209f-4819-8e12-84a9e5fe5acb.png">
<img width="312" alt="Screenshot 2022-07-27 at 21 17 17" src="https://user-images.githubusercontent.com/56361878/181343768-f65df094-58de-43ed-8abf-9564d80d34ab.png">
<img width="312" alt="Screenshot 2022-07-27 at 21 22 42" src="https://user-images.githubusercontent.com/56361878/181344710-6a2abfd8-6935-4305-9682-659e33c9e870.png">

2022-07-28 17:54 UTC, StasivPavlo requested changes

2022-08-01 15:17 UTC, v-excelsior requested changes

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/.gitignore
> +/dist
Could be removed

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/src/helpers/use-multiple-select-class-list.js
> +    const classes = ['bl-customComponent-multipleSelect', variant, ...classList];
use `cn` instead this hook

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/src/helpers/validate.js
> +    return items.split(',').map(item => ({
I think there also should be `.trim`

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/chip.js
> +export const Chip = ({ label }) => {
```
export const Chip = ({ label }) => (
  <div className="chip-item">
    <span className="chip-item__label">{ label }</span>
  </div>
)
```

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/drop-down-button.js
> +  const dropDownButtonClasses = () => {
use `cn`

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/fieldset.js
> +  const legendClasses = () => {
use `cn`

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/label.js
> +  const classes = () => {
use `cn`

2022-08-01 15:17 UTC, v-excelsior commented on components/bl-multiple-select-component/src/options/option.js
> +  const optionClassList = () => {
use `cn`

2022-08-05 21:20 UTC, v-excelsior requested changes

2022-08-05 21:20 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/input.js
> +        }
```suggestion
{ typeOfMultipleSelect === "chip" 
  ? <ChipList items={multipleSelectValue}/>
  : <span>{ inputValue }</span>
}
```

2022-08-05 21:20 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/input.js
> +  const { multipleSelectId, multipleSelectValue, typeOfMultipleSelect } = props;
What about remove 'multiple' prefix? We know from context about select is multiple, and we have no other selects.

2022-08-05 21:20 UTC, v-excelsior commented on components/bl-multiple-select-component/component.json
> +      "name": "typeOfMultipleSelect",
selectType or type

2022-08-05 21:20 UTC, v-excelsior commented on components/bl-multiple-select-component/src/helpers/validate.js
> +    }));
```suggestion
  return items
    .split(',')
    .map(i => i.trim())
    .map(i => ({ objectId: i, value: i, label: i }))
```

2022-08-15 22:32 UTC, v-excelsior requested changes

2022-08-15 22:32 UTC, v-excelsior commented on components/bl-multiple-select-component/src/helpers/validate.js
> +  if (typeof items === 'array') {
![image](https://user-images.githubusercontent.com/15347646/184729184-40c92d2f-c321-42e0-b92a-62e67caf5b61.png)

Array.isArray

2022-08-15 22:32 UTC, v-excelsior commented on components/bl-multiple-select-component/src/helpers/validate.js
> +};
```
const getId = () => Math.random().toString(16).slice(-8);
```

2022-08-15 22:32 UTC, v-excelsior commented on components/bl-multiple-select-component/src/index.js
> +      className={ cn('bl-customComponent-multipleSelect', variant, ...classList, { disable }) }>
I'm not sure, but `...classList` could be without `...`

2022-08-15 22:32 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/index.js
> +  const {
in one line?

2022-08-15 22:32 UTC, v-excelsior commented on components/bl-multiple-select-component/src/options/index.js
> +  const {
in one line?

2022-08-15 22:32 UTC, v-excelsior commented on components/bl-multiple-select-component/src/options/index.js
> +            isOptionSelected={ !!isOptionSelected }
!! should be not there - move it to place where you create variable

2022-08-15 22:32 UTC, v-excelsior commented on components/bl-multiple-select-component/src/options/index.js
> +    if (!isOptionSelected) {
swap conditions, positive should be first

2022-08-17 12:38 UTC, v-excelsior requested changes

2022-08-17 12:38 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/label.js
> +      className={ cn("label", { ["label__move-up"]: isSelectActive || selectValue.length > 0 }) }>
`selectValue.length > 0` => `selectValue.length`

2022-08-30 13:28 UTC, v-excelsior requested changes

2022-08-30 13:28 UTC, v-excelsior commented on components/bl-multiple-select-component/README.md
> +  Options      | { label: 'string', value: 'string' } |           | This property allows you to add items to be displayed in the drop down list. It's displayed on the component's logic page.
What if some certain string values we describe as `'any string'`, but it just a typeof string we write `<string>`?

2022-08-30 13:28 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/index.js
> +};
```suggestion
const getId = () => Math.random().toString(16).slice(-8)
```

2022-08-30 13:28 UTC, v-excelsior commented on components/bl-multiple-select-component/src/options/index.js
> +  }, [selectRef])
useMemo?

2022-08-30 13:28 UTC, v-excelsior commented on components/bl-multiple-select-component/src/multiple-select-field/index.js
> +};
We have two similar getId functions, remove one of them

2022-08-30 13:28 UTC, v-excelsior commented on components/bl-multiple-select-component/src/index.js
> +    if (!isOptionsOpen) {
positive condition first

2022-09-07 08:21 UTC, Valodya commented on components/bl-multiple-select-component/README.md
> +# Multiple Select
please fix the readme to our standart

2022-09-07 08:22 UTC, Valodya commented
please add a preview and thumbnail image

2022-09-07 08:24 UTC, Valodya commented on components/bl-multiple-select-component/src/helpers/use-on-click-outside.js
> +export const useOnClickOutside = (ref, handler) => {
```
export const useOnClickOutside = (ref, handler) => {
  useEffect(() => {
    const listener = event => {
      if (!ref.current || ref.current.contains(event.target)) {
        return;
      }
  
      handler(event);
    };

    document.addEventListener('mousedown', listener);
    document.addEventListener('touchstart', listener);

    return () => {
      document.removeEventListener('mousedown', listener);
      document.removeEventListener('touchstart', listener);
    };
  }, [ref, handler]);
};
```

2022-09-07 08:25 UTC, Valodya commented on components/bl-multiple-select-component/src/helpers/validate.js
> +    return items;
this line is redundant

2022-09-07 08:27 UTC, Valodya commented on components/bl-multiple-select-component/src/multiple-select-field/input.js
> +export function Input(props) {
```
export function Input({ type, selectId, selectValue }) {
```

2022-09-07 08:31 UTC, Valodya commented on components/bl-multiple-select-component/src/options/index.js
> +  return (
```
const selectedValuesMap = useMemo(() => {
  return selectValue.reduce((m, { objectId }) => ({...m, [objectId]:1 }), {})
},[selectValue])

return (
    <div className="options" style={{ transform: `translateY(-${ margin }px)` }} ref={ selectRef }>
      { options.map(option => (
          <Option
            key={ option.objectId }
            type={ type }
            option={ option }
            isOptionSelected={ selectedValuesMap[option.objectId] }
            handleSelectValue={ handleSelectValue }
          />
        )) }
    </div>
  );
```

2022-09-07 08:32 UTC, Valodya commented on components/bl-multiple-select-component/src/options/option.js
> +export function Option(props) {
```
export function Option({ type, option, selected, onSelect }) {
```

2022-09-07 08:33 UTC, Valodya commented on components/bl-multiple-select-component/src/multiple-select-field/label.js
> +      className={ cn("label", { ["label__move-up"]: isSelectActive || selectValue.length }) }>
`cn("label", { 'label__move-up': isSelectActive || selectValue.length })`

2022-09-07 08:34 UTC, Valodya commented on components/bl-multiple-select-component/src/options/option.js
> +      className={ cn("option", { ['option__selected']: isOptionSelected }) }>
`cn('option', { option__selected: isOptionSelected })`

2022-09-21 12:12 UTC, merged