MARKET-1546 Ace Editor component
Backendless/ui-builder-library pull request #214
Opened 2023-01-23 23:52 UTC by Saharij

<img width="727" alt="Screenshot 2023-01-24 at 01 40 59" src="https://user-images.githubusercontent.com/56361878/214178006-77ca829c-e173-4e20-bb2d-7a9d11bd79ed.png">
<img width="727" alt="Screenshot 2023-01-24 at 01 45 26" src="https://user-images.githubusercontent.com/56361878/214178029-380ffd4d-882a-451c-bdba-55ce9348c0de.png">
<img width="727" alt="Screenshot 2023-01-24 at 01 51 10" src="https://user-images.githubusercontent.com/56361878/214178036-68c4996c-9015-4c57-8151-7f8f30689d92.png">

2023-02-01 20:51 UTC, StasivPavlo requested changes

2023-02-01 20:51 UTC, StasivPavlo commented on components/bl-ace-editor-component/src/index.js
> +  }, [rootRef]);
Now we don't need this. Do how on example
Example:
```
export default function CustomUIComponent({ component, elRef }) {

 if(!component.display){
   return null
 }
 
  return (
    <div ref={elRef}>
      Custom Component with EL Ref
    </div>
  )
}
```

2023-02-03 12:38 UTC, v-excelsior requested changes

2023-02-03 12:38 UTC, v-excelsior commented on components/bl-ace-editor-component/src/index.js
> +        } }
Create options before passing them to component

2023-02-03 12:38 UTC, v-excelsior commented on components/bl-ace-editor-component/src/index.js
> +  }, []);
```suggestion
  const onChangeHandler = useCallback(value => {
    setEditorValue(value);
    onChange({ value });
  }, []);
```

2023-02-03 12:38 UTC, v-excelsior commented on components/bl-ace-editor-component/src/index.js
> +  const [editorValue, setEditorValue] = useState('');
`useState(value)` ?

2023-02-03 12:38 UTC, v-excelsior commented on components/bl-ace-editor-component/src/index.js
> +        readOnly={ disabled }
> The difference between disabled and readonly is that read-only controls can still function and are still focusable, whereas disabled controls can not receive focus and are not submitted with the form and generally do not function as controls until they are enabled.

Is it really disabled? May be we need to use same definition as library(readonly)?

2023-02-15 17:08 UTC, merged