BKNDLSS-31144 Purpose of "value" select in settings
Backendless/ui-builder-library pull request #243
Opened 2023-01-31 17:41 UTC by Saharij

2023-01-31 18:43 UTC, v-excelsior commented on components/bl-multiple-select-component/component.json
> +      "settingTooltip": "Enter the value separated by a comma.",
Also, will be good if add it to readme.

2023-02-02 08:40 UTC, v-excelsior requested changes

2023-02-02 08:40 UTC, v-excelsior commented on components/bl-multiple-select-component/src/index.js
> +  }, [rootRef]);
Make changes according to https://bugs.backendless.com/browse/BKNDLSS-31234

2023-02-02 08:41 UTC, Saharij commented on components/bl-multiple-select-component/component.json
> +      "settingTooltip": "Enter the value separated by a comma.",
did it in another ticket

2023-02-03 11:51 UTC, merged