MARKET-1641 Is there a way to make popover position dynamic?
Backendless/ui-builder-library pull request #281
Opened 2023-02-14 08:47 UTC by StasivPavlo

2023-02-14 15:58 UTC, v-excelsior requested changes

2023-02-14 15:58 UTC, v-excelsior commented on components/bl-popover-component/src/Tooltip.js
> +  const [validatePosition, setValidatePosition] = useState(position);
validate - it's an action, I believe there should be valid or validated

2023-02-14 15:58 UTC, v-excelsior commented on components/bl-popover-component/src/helpers.js
> +    left  : () => (
left => Position.LEFT - should be same as for ShiftHandler

2023-02-14 15:58 UTC, v-excelsior commented on components/bl-popover-component/src/helpers.js
> +    const side = Position[key];
Object.values(Position).forEach

2023-02-14 15:58 UTC, v-excelsior commented on components/bl-popover-component/src/helpers.js
> +  const PositionCheck = {
PositionCheck - PositionValidator

2023-02-14 15:58 UTC, v-excelsior commented on components/bl-popover-component/src/helpers.js
> +      window.innerHeight - targetBottom >= contentHeight
I'm not sure if it good approach, and my offer is to do it(check for intersection) through IntersectionObserver, but I'm not insisting.

2023-02-23 09:34 UTC, StasivPavlo commented on components/bl-popover-component/src/helpers.js
> +    const side = Position[key];
but return doesn't work inside forEach

2023-02-27 08:22 UTC, merged