MARKET-1644 Inner Image Zoom
Backendless/ui-builder-library pull request #293
Opened 2023-02-17 09:18 UTC by Fialkaksu

The InnerImageZoom component allows the user to apply an image zoom effect inside that image in the application.

[MARKET-1644](https://bugs.backendless.com/browse/MARKET-1644)
[UI-Builder](https://develop.backendless.com/app/TestComponentsApp/ui-builder/InnerImageZoom/pages/landing)
[Desktop Preview](https://populardowntown.backendless.app/api/files/ui-builder/containers/InnerImageZoom/index.html?page=landing)

![image](https://user-images.githubusercontent.com/46996947/219603488-030d3a92-d536-4164-8275-4b3efca4678d.png)
onHover:
![image](https://user-images.githubusercontent.com/46996947/219603708-0f0da721-f584-4ca5-9175-6ad82624bb9e.png)

2023-02-17 12:15 UTC, serhmel commented on components/bl-innerImageZoom-component/src/index.js
> +    const y = ((event.pageY - top - window.pageYOffset) / height) * 100;
empty line after variables

2023-02-17 12:15 UTC, serhmel commented on components/bl-innerImageZoom-component/README.md
> +| On Mouse Move Event | Triggered when the user moves the mouse over or touches the image. | `{event: Object}` |
`{event: Object}` => Event: `Object` ?

2023-02-20 15:01 UTC, serhmel commented on components/bl-innerImageZoom-component/src/index.js
> +  }), [src, zoomPosition, zoom]);
```suggestion
  const figureStyle = useMemo(() => ({
    backgroundImage   : `url(${ src })`,
    backgroundPosition: zoomPosition,
    backgroundSize    : `${ zoom * 100 }% ${ zoom * 100 }%`,
  }), [src, zoomPosition, zoom]);
```

2023-02-21 17:11 UTC, v-excelsior commented on components/bl-innerImageZoom-component/README.md
> +| Image Source <br> `source` | *Text*   | `https://content.r9cdn.net/rimg/dimg/6d/56/5bd0abd4-city-26896-1670df92320.jpg?width=1366&height=768&xhint=1567&yhint=925&crop=true` | Image Source Logic | Y
Image Source -> URL

2023-02-21 17:17 UTC, v-excelsior commented on components/bl-innerImageZoom-component/README.md
> +| Image Source <br> `source` | *Text*   | `https://content.r9cdn.net/rimg/dimg/6d/56/5bd0abd4-city-26896-1670df92320.jpg?width=1366&height=768&xhint=1567&yhint=925&crop=true` | Image Source Logic | Y
Try to not use external resources for images. Try to use base64 or selfhosted resources.
Also we must discuss it on meeting

2023-02-21 17:20 UTC, v-excelsior commented on components/bl-innerImageZoom-component/README.md
> +| Zoom <br> `zoomIn`         | *Number* | 2                                                                                                                                    |                    | N
Would be better to use percents for that. 140 looks for me better than 1.4(or 1,4)

2023-02-21 17:24 UTC, v-excelsior commented on components/bl-innerImageZoom-component/src/index.js
> +  const figureStyle = useMemo(() => ({
useStyles hook

2023-02-21 17:25 UTC, v-excelsior commented on components/bl-innerImageZoom-component/src/index.js
> +  const src = useMemo(() => source, [source]);
That do nothing

2023-02-21 17:25 UTC, v-excelsior commented on components/bl-innerImageZoom-component/src/index.js
> +  const zoom = useMemo(() => Math.max(1, zoomIn), [zoomIn]);
useMemo calculation is harder than comparison of two numbers

2023-02-21 17:27 UTC, v-excelsior commented on components/bl-innerImageZoom-component/src/index.js
> +  const [zoomPosition, setZoomPosition] = useState('0% 0%');
'0% 0%' - magic string, try avoid them

const DEFAULT_ZOOM_POSITION

2023-03-07 14:00 UTC, v-excelsior requested changes

2023-03-07 14:00 UTC, v-excelsior commented on components/bl-innerImageZoom-component/src/index.js
> +  const figureStyle = useStyles(source, zoomPosition, zoom);
There are no strict rules, but try to split it in some order.

For example here we could

```
const { classList, style, display, source, zoomIn } = component; //Works with props
const { onMouseOver, onMouseOut, onMouseMove } = eventHandlers;

const [zoomPosition, setZoomPosition] = useState(DEFAULT_ZOOM_POSITION);//Default hooks like useState useRef useMemo

const figureStyle = useStyles(source, zoomPosition, zoom); // Our custom hooks

const zoom = Math.max(100, zoomIn); //regular calculations
```

2023-03-14 08:36 UTC, merged