BKNDLSS-28512 Badge
Backendless/ui-builder-library pull request #3
Opened 2022-06-10 14:43 UTC by serhmel

2022-06-15 00:03 UTC, v-excelsior requested changes

2022-06-15 14:44 UTC, serhmel commented on components/bl-badge-component/styles/index.less
> +@bl-customComponent-badge-content-color: @bl-customComponent-badge-textColor;
It is used in @bl-customComponent-badge-content-iconColor and @bl-customComponent-badge-content-textColor variables.

2022-06-16 21:30 UTC, v-excelsior commented on components/bl-badge-component/src/badge.js
> +  const badgeForms = {
Constant should be outside of component or in external file

2022-06-16 21:34 UTC, v-excelsior commented on components/bl-badge-component/src/badge.js
> +  const badgeForms = {
Also types map should be in uppercase.

BadgeForms
BadgeRadiusMap

2022-06-16 21:36 UTC, v-excelsior commented on components/bl-badge-component/component.json
> +      "type": "number"
Is it still number? I believe after our disscussion about rem/em/% there should be a `text` type

2022-06-17 09:40 UTC, Valodya commented on components/bl-badge-component/src/content/image.js
> +  const styles = useMemo(() => ({
as far as I know there is no reason to wrap style with useMemo if they go to a native DOM component

2022-06-21 08:10 UTC, v-excelsior commented on components/bl-badge-component/src/content.js
> +import { Icon } from './content/icon';
Create an index with reexporting all types of content and here will be

import { Icon, Image, Text } from './content';

2022-06-21 08:15 UTC, v-excelsior commented on components/bl-badge-component/component.json
> +      "label": "Icon",
In readme we should describe where we could get  a type of icons.

2022-06-21 08:16 UTC, v-excelsior commented on components/bl-badge-component/component.json
> +      "name": "text",
text -> textContent ?

Too general name for property

2022-06-22 23:18 UTC, v-excelsior approved these changes

2022-08-01 15:20 UTC, v-excelsior requested changes

2022-08-01 15:20 UTC, v-excelsior commented on components/bl-badge-component/.gitignore
> +/dist
could be removed

2022-08-01 15:20 UTC, v-excelsior commented on components/bl-badge-component/component.json
> +      "name": "badgeAlignment",
I think as we haven't any other Aligments, we could rename from `badgeAlignment` to `aligment`, at least in code(handler names)

Same for other properties

2022-08-01 15:20 UTC, v-excelsior commented on components/bl-badge-component/src/index.js
> +    <div className={ 'bl-customComponent-badge ' + classList.join(' ') } style={{ padding }}>
use `cn`

2022-08-03 18:41 UTC, Valodya commented on components/bl-badge-component/src/badge.js
> +  if (!badgeVisibility) {
can we use `display` instead?

2022-08-03 19:30 UTC, merged