BKNDLSS-29165 Stripe Payment
Backendless/ui-builder-library pull request #30
Opened 2022-08-18 10:33 UTC by serhmel

<img width="246" alt="Screenshot_1" src="https://user-images.githubusercontent.com/93279075/185372268-44ab5d75-2565-4b2b-8d91-03cb39ae1a4a.png">  <img width="245" alt="Screenshot_2" src="https://user-images.githubusercontent.com/93279075/185372246-1e9a88e7-0969-4b21-bef9-7fd329fadfd1.png"> 
<img width="243" alt="Screenshot_6" src="https://user-images.githubusercontent.com/93279075/185372650-31532ba5-d975-41b4-a5cb-36f0320f74ed.png"> <img width="244" alt="Screenshot_7" src="https://user-images.githubusercontent.com/93279075/185372675-bd46e755-1fc4-4767-be32-0ad77ad816c5.png"> <img width="245" alt="Screenshot_9" src="https://user-images.githubusercontent.com/93279075/185372771-f3393de8-f8c6-4cb9-8137-c4a0ad6fb0ae.png">
<img width="221" alt="Screenshot_3" src="https://user-images.githubusercontent.com/93279075/185372364-6a07e976-00e6-4837-a236-3a04155899db.png"> <img width="224" alt="Screenshot_4" src="https://user-images.githubusercontent.com/93279075/185372464-5f1dacb9-5b30-472e-a7e8-0493e2997fca.png"> <img width="223" alt="Screenshot_5" src="https://user-images.githubusercontent.com/93279075/185372477-9987db5f-9a49-49f1-987e-bb4f82832bc0.png">

UI Preview:
<img width="270" alt="ui_preview" src="https://user-images.githubusercontent.com/93279075/185374375-a260d875-f875-464c-adf1-d491c49be086.png">

2022-08-22 11:22 UTC, Saharij commented on components/bl-stripe-payment-component/src/index.js
> +    <div className={ cn(classList, 'bl-customComponent-stripe-payment') }>
In my opinion, it is better when first there will be a main class ('bl-customComponent-stripe-payment'), and then a classList
`cn('bl-customComponent-stripe-payment', classList)`

2022-08-22 11:22 UTC, Saharij commented on components/bl-stripe-payment-component/src/payment-components/billing-details.js
> +          key={ index }
The property `key` must be the first

2022-08-30 14:21 UTC, v-excelsior requested changes

2022-08-30 14:21 UTC, v-excelsior commented on components/bl-stripe-payment-component/README.md
> +<dd>Checkbox for determining whether the payment form contains a field for the address. Unchecked by default.</dd>
Could we describe checkbox value using booleans? true/false

2022-08-30 14:21 UTC, v-excelsior commented on components/bl-stripe-payment-component/src/helpers/use-card-element.js
> +      'address_city'   : formField.city ? formField.city.value : undefined,
```suggestion
      'address_city'   : formField?.city?.value,
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

And for others

2022-08-30 14:21 UTC, v-excelsior commented on components/bl-stripe-payment-component/src/payment-form.js
> +  };
move into function below the component

2022-08-30 14:21 UTC, v-excelsior commented on components/bl-stripe-payment-component/src/payment-form.js
> +      <button type="submit" disabled={ isDisabled }>{ `Pay ${ amount || 0 } ${ currency || '' }` }</button>
`isDisabled` -> `disabled` or `whatDisabled`(e.g. `veryDangerousButtonDisabled`)

2022-08-31 16:34 UTC, Valodya commented on components/bl-stripe-payment-component/README.md
> +### Styles and Settings
please change the readme according to the new standard https://github.com/Backendless/ui-builder-library/blob/main/components/bl-leafletMap-component/README.md

2022-08-31 16:35 UTC, Valodya commented on components/bl-stripe-payment-component/component.json
> +  "blockUI": "<div data-module-type=\"system\" data-module-id=\"block\" data-display data-uid=\"acff8fb8153593183ee6c5a860e7b7ab\" style=\"display:flex;flex-shrink:0;flex-direction:column;padding:0 0
I believe it should not be here

2022-08-31 16:38 UTC, Valodya commented on components/bl-stripe-payment-component/src/helpers/use-card-element.js
> +        if (onSuccessEvent) {
not sure, but I guess all defined event handlers always exist

2022-09-07 06:50 UTC, merged