MARKET-1331 Skeleton
Backendless/ui-builder-library pull request #33
Opened 2022-08-24 10:43 UTC by StasivPavlo

![image](https://user-images.githubusercontent.com/99363993/186399119-52b4f26f-9ad3-4454-9536-9594a4493050.png)
![image](https://user-images.githubusercontent.com/99363993/186399222-4e8f7bd0-5f24-482b-bbb1-ca923b8071f3.png)

2022-08-24 12:05 UTC, v-excelsior requested changes

2022-08-24 12:05 UTC, v-excelsior commented on components/bl-skeleton-component/component.json
> +      "label": "Width(px)",
I assume that property should accept any values, for example 100%

2022-09-07 06:36 UTC, Valodya commented on components/bl-skeleton-component/src/index.js
> +      style={ { ...style, width: width ? width : '100%', height: height ? height : '100%' } }>
`width: width || '100%'`

2022-09-07 06:37 UTC, Valodya commented on components/bl-skeleton-component/src/index.js
> +      className={ cn('bl-customComponent-skeleton', `${ variant }`, `${ animation }`, classList) }
```
cn('bl-customComponent-skeleton',  variant, animation, classList)
```

2022-09-07 06:39 UTC, Valodya commented on components/bl-skeleton-component/README.md
> +# Skeleton
please correct the readme following rules of our etalon

2022-09-07 06:41 UTC, Valodya commented
@StasivPavlo also please add a preview and a thumbnail image

2022-09-21 09:32 UTC, merged