BKNDLSS-31618 [MapBox Component] On mobile devices display directions under the map
Backendless/ui-builder-library pull request #335
Opened 2023-03-02 17:44 UTC by addKiwi

2023-03-02 18:13 UTC, v-excelsior commented on components/bl-mapbox-component/src/helpers.js
> +      accessToken: mapboxgl.accessToken,
Could we get all needed in this function parts of mapboxgl using destruction?

`const {Map, accessToken, FullscreenControl ... } = Mapbox`


Also change it

`import mapboxgl from './lib/mapbox';` => `import Mapbox from './lib/mapbox';`

2023-03-02 18:20 UTC, v-excelsior commented on components/bl-mapbox-component/src/helpers.js
> +  })(navigator.userAgent || navigator.vendor || window.opera);
`return /long rexexp/i.test(a.substr(0, 4))`

I'm think we doesn't need to IIFE here

2023-03-03 10:07 UTC, v-excelsior requested changes

2023-03-03 10:38 UTC, addKiwi commented on components/bl-mapbox-component/src/helpers.js
> +const appendMobileMark = (directions, mapRef, mapContainerRef) => {
![image](https://user-images.githubusercontent.com/29707734/222698832-32ab51c8-e25d-48d9-b4f5-12d93d1d9ddf.png)

2023-03-03 10:49 UTC, addKiwi commented on components/bl-mapbox-component/src/helpers.js
> +    const isFit = mapRef.current.transform.width > 570;
No, this only works for the first load. To make it responsive, I'm not sure I'll have time to finish and release it by the end of the day. Talked to Bohdan, it's fine and we will update it after the release.

2023-03-03 11:03 UTC, merged