MARKET-1772 [Rating reviews component]
Backendless/ui-builder-library pull request #743
Opened 2023-08-28 15:49 UTC by addKiwi

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/subcomponents/progress-bar.js
> +  const { getRatingScore } = eventHandlers;
```suggestion
export const ProgressBar = ({ value, maxValue, color, eventHandlers: { getRatingScore } }) => {
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/subcomponents/progress-bar.js
> +  const percent = `${Math.round(value * 100 / maxValue)}%`;
```suggestion
  const percent = `${ Math.round(value * 100 / maxValue) }%`;
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +const { EmptyStar, FilledStar, EmptyHeart, FilledHeart } = icons;
I guess we can import like this after some manipulation in icons.js.
```
import { EmptyStar, FilledStar, EmptyHeart, FilledHeart } from './icons';
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +) => {
As an alternative

```suggestion
const OneColorReview = props => {
  const { width, average, maxValue, color, iconSize, totalReviews, reviewData, localizations, eventHandlers } = props;
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +          <span className="average-value"> {average} {localizations.averageText} {maxValue} </span>
```suggestion
          <span className="average-value">{ average } { localizations.averageText } { maxValue }</span>
```
also we can wrap each property with separate `span`

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +            Filled={ FilledStar }
Why we pass `EmptyStar `and `FilledStar `components as a property and don't import it in icon-row.js file ?

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +          <span className="total-text">{`${totalReviews} ${localizations.reviewsText}`}</span>
```suggestion
          <span className="total-text">{ `${ totalReviews } ${ localizations.reviewsText }` }</span>
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +                  Filled={ FilledStar }
The same about import  `EmptyStar` and `FilledStar`  in icon-row.js file.

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +                  value={ maxValue-i }
```suggestion
                  value={ maxValue - i }
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +                  size={ iconSize } />
`/>` from new line

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +                <span className="value">{el.value}</span>
```suggestion
                <span className="value">{ el.value }</span>
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +          }
```suggestion
          { reviewData.map((el, i) => (
            <ProgressBar
              key={ i }
              eventHandlers={ eventHandlers }
              maxValue={ totalReviews }
              value={ el.value }
              color={ color }
            />
          )) }
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +    <div className="twoColorReview" style={{ 'width': width }}>
```suggestion
const TwoColorReview = ({ width, maxValue, color, iconSize, totalReviews, reviewData, eventHandlers }) => (
  <div className="twoColorReview" style={{ 'width': width }}>
```

or

```suggestion
const TwoColorReview = props => {
  const { width, maxValue, color, iconSize, totalReviews, reviewData, eventHandlers } = props;
  
  return (
    <div className="twoColorReview" style={{ 'width': width }}>
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +                <span className="number">{maxValue - i}</span>
```suggestion
              <div className="icon-container" key={ i }>
                <span className="number">{ maxValue - i }</span>
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +                <span className="icon" style={{ 'height' : iconSize, 'width': iconSize }}><FilledStar/></span>
```suggestion
                <span className="icon" style={{ 'height': iconSize, 'width': iconSize }}>
                  <FilledStar/>
                </span>
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +          }
```suggestion
          { reviewData.map((el, i) => (
            <span key={ i }>{ el.value }</span>
          )) }
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +};
The same with   
`const { width, average, ... } = props;`
imports of `EmptyHeart `and `FilledHeart`
spaces inside of curly braces
start to srite in the same line when you open curly braces in jsx

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/src/views.js
> +export default ViewsMap;
Use the default import for the root component only.
```suggestion
export const ViewsMap = {
  oneColor  : OneColorReview,
  twoColor  : TwoColorReview,
  multiColor: MultiColorReview,
};
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/styles/index.less
> +
redundant empty line

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/styles/index.less
> +@bl-cutomComponent-customer-reviews-color: @appTextColor;
```suggestion
@bl-customComponent-customer-reviews-color: @appTextColor;
```

2023-08-29 10:54 UTC, serhmel commented on components/bl-rating-reviews/README.md
> +| Review Data            | *JSON*                                               |               | Review Data Logic | YES          | YES        | This handler adds review data for component. Watch [C
I guess signature should contain the data type of the property value.

2023-08-31 08:14 UTC, v-excelsior requested changes

2023-08-31 08:14 UTC, v-excelsior commented on components/bl-rating-reviews/src/icons.js
> +);
empty lines

2023-08-31 08:14 UTC, v-excelsior commented on components/bl-rating-reviews/src/icons.js
> +export const icons = { EmptyStar, FilledStar, EmptyHeart, FilledHeart };
You already export icons

2023-08-31 08:14 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +        <div className="progress-bar-container">
Find in code `progress-bar-container` it was written not once, but each time different code style. Also as far as it is duplicated, you could make it a component.

2023-08-31 08:14 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +        </div>
Make it component. 
And pass reviewData.length into it if it could be different

2023-08-31 08:14 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +          }) }
Try to avoid JS in JSX. Make it component

2023-08-31 08:14 UTC, v-excelsior commented on components/bl-rating-reviews/src/index.js
> +  const maxValue = useMemo(() => processedData.length, [processedData.length]);
Redundant action.

It's primitive, not object, so that doesn't prevent rerenders.

2023-08-31 18:04 UTC, v-excelsior requested changes

2023-08-31 18:04 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +      <div className="progress-bar-fill" style={ { 'width': percent, 'background': color } }/>
create styles object

2023-08-31 18:04 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +    <div className="oneColorReview" style={ { 'width': width, 'color': color } }>
styles object

2023-08-31 18:04 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +    <div className="twoColorReview" style={ { 'width': width } }>
styles object with useMemo

2023-08-31 18:04 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +    <div className="multiColorReview" style={ { 'width': width } }>
same

2023-09-04 12:20 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +  const resultRow = Array.from({ length: maxValue }, (_, i) => {
```suggestion
  }), [iconType]);
  
  const resultRow = Array.from({ length: maxValue }, (_, i) => {
```

2023-09-04 12:21 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +  const { FilledIcon, EmptyIcon } = useMemo(() => ({
```suggestion
  const styles = { fill: color, width: size, height: size };
  
  const { FilledIcon, EmptyIcon } = useMemo(() => ({
```

2023-09-04 12:25 UTC, v-excelsior requested changes

2023-09-04 12:25 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +  const styles = { width, color };
useMemo

2023-09-04 12:25 UTC, v-excelsior commented on components/bl-rating-reviews/src/views.js
> +  const Icon = IconsMap[iconType].filled;
useMemo

2023-09-04 12:25 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +  const styles = { width: percent, background: color };
useMemo

Please, pay attention for all places when I make comments at PR

2023-10-11 21:05 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +    return (reviewData.map(({ value }) => Math.round(calculatePercent(value, totalReviews))));
```suggestion
    return reviewData.map(({ value }) => Math.round(calculatePercent(value, totalReviews)));
```

2023-10-11 21:09 UTC, v-excelsior requested changes

2023-10-11 21:09 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +  const resultRow = Array.from({ length: maxValue }, (_, i) => {
useMemo

2023-10-11 21:09 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +  const resultRow = Array.from({ length: maxValue }, (_, i) => {
resultRow -> icons

2023-10-11 21:09 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +      { resultRow.map((el, key) => (
`resultRow.map((el, key)` -> `icons.map((icon, i)`

2023-10-11 21:09 UTC, v-excelsior commented on components/bl-rating-reviews/src/subcomponents.js
> +      { percentsArray.map((percent, i) => (<span key={ i }>{ `${ percent }%` }</span>)) }
```suggestion
      { percentsArray.map((percent, i) => (
      <span key={ i }>{ `${ percent }%` }</span>)
      ) }
```

2023-10-12 18:28 UTC, merged