MARKET-1674 [Navigation Dots Component]
Backendless/ui-builder-library pull request #777
Opened 2023-09-21 12:18 UTC by Fialkaksu

The Navigation Dots сomponent is a navigation element designed for use in web applications. It provides a visually appealing way to navigate through different sections on a webpage.

[MARKET-1674](https://bugs.backendless.com/browse/MARKET-1674)
[UI-Builder](https://develop.backendless.com/app/TestComponentsApp/ui-builder/NavigationDots/pages/landing)
[Desktop Preview](https://populardowntown.backendless.app/api/files/ui-builder/containers/NavigationDots/index.html?page=landing)

![image](https://github.com/Backendless/ui-builder-library/assets/46996947/f0006ed4-e24c-4ab0-87b0-e317c85eccb7)

2023-09-21 15:33 UTC, serhmel commented on components/bl-navigation-dots/README.md
> +| On Click | when the user clicks on the component. | activeSection: `Element` |
`activeSection `-> `Active Section` ?

2023-09-26 08:47 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +    }
there should be a function that will make it more readable

2023-09-26 08:49 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +    }, 1000);
could be one lined

2023-09-26 08:49 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +              ) }
one line?

2023-09-26 08:50 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +          </li>
Component?

2023-09-26 08:50 UTC, v-excelsior commented on components/bl-navigation-dots/styles/index.less
> +      pointer-events: auto !important;
Why here is an important?

2023-09-26 08:52 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +        { sections?.map((section, index) => (
How about add `if` statement that will check for sections and print warning if they are invalid?

2023-09-26 08:54 UTC, v-excelsior commented on components/bl-navigation-dots/README.md
> +| Sections <br> `sections`                    | *JSON*                                         | `[]`              | Sections Logic           | YES          | NO         | This logic allows you to sp
I'm not clearly understand how we could create dynamic count of sections using data binding?

2023-09-26 08:55 UTC, v-excelsior commented on components/bl-navigation-dots/README.md
> +| On Click | when the user clicks on the component. | Active Section: `Element` |
On Section Change event?

2023-10-11 09:08 UTC, v-excelsior requested changes

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +function anchorValidation(anchors) {
anchorValidation -> validateAnchors

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +      console.error("Error: anchor in 'anchors' prop is missing, invalid, or contains non-string value in NavigationDotsComponent.");
Not quite clear which anchor is missing. How about validate them one by one, and if some is invalid - print it with index in array?

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +    setTimeout(() => setScrollEnabled(true), 1000);
Clean timeouts?

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +  }, [anchors]);
one line

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +
redundant line

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +      }
```suggestion
      { anchors && (
        <Nav
          anchors={ anchors }
          activeDotIndex={ activeDotIndex }
          dotShape={ dotShape }
          tooltip={ tooltip }
          dotClickHandler={ dotClickHandler }
        />
      )}
```

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +          dotClickHandler={ dotClickHandler }
dotClickHandler -> onItemClick

2023-10-11 09:08 UTC, v-excelsior commented on components/bl-navigation-dots/src/index.js
> +  }
Array.find?

2023-10-11 19:18 UTC, merged