MARKET-1670 Image List Component
Backendless/ui-builder-library pull request #835
Opened 2023-10-24 10:36 UTC by Fialkaksu

The Image List displays a collection of images in an organized grid.

[MARKET-1670](https://bugs.backendless.com/browse/MARKET-1670)
[UI-Builder](https://develop.backendless.com/app/TestComponentsApp/ui-builder/ImageList/pages/landing)
[Desktop Preview](https://populardowntown.backendless.app/api/files/ui-builder/containers/ImageList/index.html?page=landing)

![image](https://github.com/Backendless/ui-builder-library/assets/46996947/5186649a-6a0a-4424-a2b9-919c2ae1befe)

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/component.json
> +      "handlerDescription": "Specifies a JSON array containing data of the image list items. Signature of items list: [ <Item> ]. Signature of item: { img: String, title: String, rows: Number, cols:
Not sure about signatures in handler tooltips.

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/src/index.js
> +  };
use at the beginning

`  const { onItemClick, onTitleClick, onImageClick } = eventHandlers;`

and then we can remove it

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/src/index.js
> +                style={{ height:`${ titleBarHeight }px` }}
```suggestion
                style={{ height: `${ titleBarHeight }px` }}
```

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/src/index.js
> +        '--image-height-common': isItemBarBelow ? `calc(100% - ${ titleBarHeight }px)` : '100%',
```suggestion
      '--image-height'       : isItemBarBelow ? `${ deltaHeight }px` : `${ rowHeight }px`,
      '--image-height-even'  : isItemBarBelow ? `${ deltaHeightEven }px` : `${ heightEven }px`,
      '--image-height-common': isItemBarBelow ? `calc(100% - ${ titleBarHeight }px)` : '100%',
```

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/src/index.js
> +                onClick={ e => onTitleClick(e, item.title, item) }/>
`/>` from new line

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/src/index.js
> +              onClick={ e => onImageClick(e, item.img, item) }/>
`/>` from new line

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/src/lib/mui.js
> +/**
513,4 kB 
Not sure that all of this is required for your component

2023-10-25 09:42 UTC, serhmel commented on components/bl-image-list/src/index.js
> +                rows={ item.rows }
To me it is not good idea duplicating `item` for each property.

2023-10-30 07:36 UTC, serhmel commented on components/bl-image-list/src/index.js
> +    gap } = component;
in single line

2023-10-30 07:36 UTC, serhmel commented on components/bl-image-list/src/index.js
> +        variant={ listVariant }>
in single line

2023-10-30 07:36 UTC, serhmel commented on components/bl-image-list/src/index.js
> +          />
in single line

2023-10-30 07:36 UTC, serhmel commented on components/bl-image-list/src/index.js
> +      />
in single line

2023-10-30 07:36 UTC, serhmel commented on components/bl-image-list/src/index.js
> +    });
```suggestion
    return ({
      '--image-height'       : isItemBarBelow ? `${ deltaHeight }px` : `${ rowHeight }px`,
      '--image-height-even'  : isItemBarBelow ? `${ deltaHeightEven }px` : `${ heightEven }px`,
      '--image-height-common': isItemBarBelow ? `calc(100% - ${ titleBarHeight }px)` : '100%',
    });
```

2023-11-02 08:37 UTC, v-excelsior requested changes

2023-11-02 08:37 UTC, v-excelsior commented on components/bl-image-list/README.md
> +| Item Data <br> `itemData`                  | *JSON*                                                    | `[]`          | Item Data Logic | YES          | YES        | Specifies a JSON array contain
`Item Data` -> `Items` or `Items Data`

2023-11-02 08:37 UTC, v-excelsior commented on components/bl-image-list/README.md
> +| Variant <br> `listVariant`                 | *Select* <br> [`standard`, `quilted`, `woven`, `masonry`] | `standard`    |                 | NO           | YES        | Controls the variant of image
`Variant` -> `Layout`

2023-11-02 08:37 UTC, v-excelsior commented on components/bl-image-list/src/index.js
> +  }, [itemData]);
we can avoid using of this useState and useEffect

2023-11-02 08:37 UTC, v-excelsior commented on components/bl-image-list/src/index.js
> +          <Item key={ item.img } item={ item } component={ component } eventHandlers={ eventHandlers }/>
`item.img` is not uniq

Also, for the future(you should not change it now): `img` -> `imgURL`

2023-11-02 08:37 UTC, v-excelsior commented on components/bl-image-list/src/index.js
> +          <Item key={ item.img } item={ item } component={ component } eventHandlers={ eventHandlers }/>
Do not pass `component` here - use only needed props.

2023-11-02 15:23 UTC, v-excelsior approved these changes

2023-11-02 15:23 UTC, merged