MARKET-1336 Treemap
Backendless/ui-builder-library pull request #96
Opened 2022-09-21 20:31 UTC by Saharij

<img width="502" alt="Screenshot 2022-09-21 at 23 31 13" src="https://user-images.githubusercontent.com/56361878/191604446-2eeb4914-b2dc-4295-ba32-3d2aa2a3fd13.png">

2022-09-23 17:44 UTC, StasivPavlo commented on components/bl-treemap-component/src/index.js
> +  const { classList, display, disabled, label, valueUnit, width, height, data } = component;
add property `style`

2022-10-04 08:56 UTC, v-excelsior requested changes

2022-10-04 08:56 UTC, v-excelsior commented on components/bl-treemap-component/README.md
> +Treemap is a component of Backendless UI-Builder designer. The main purpose of the component is proportional display of data. Also, the [react-d3-treemap](https://github.com/jquintozamora/react-d3-tr
Please, take a look at this library

![image](https://user-images.githubusercontent.com/15347646/193777438-15ff7d8b-37ba-482b-bcdd-1f104afeb8df.png)

I don't think it's enough level of code quality to share it with customers which pay for our services.

Please, found the more popular solution with a rich API, or write it by yourself - to have the possibility of delivering new features.

2022-12-21 15:04 UTC, v-excelsior requested changes

2022-12-29 12:39 UTC, Saharij commented on components/bl-treemap-component/src/index.js
> +        idMemberPath="label"
Actually, we don't need this attribute at all.

2023-01-03 09:25 UTC, Valodya commented on components/bl-treemap-component/src/index.js
> +import { IgrTreemap } from './lib/igr-treemap.umd.js';
```
import { IgrTreemap, IgrTreemapModule } from './lib/igr-treemap.umd.js';
```

2023-01-03 13:57 UTC, Valodya approved these changes

2023-01-03 13:57 UTC, merged